channels:
- conda-forge
dependencies:
- pip:
  - flit
  - beni
- python>=3.6
- pip
- bayesian-optimization>=1.1.0
- frozendict>=2.0.3
- mpi4py>=3.0.3
- networkx>=2.4
- numba>=0.54.0
- numpy>=1.19
- scipy>=1.5.0
- black
- ipython
- jupyterlab>=3.2
- matplotlib-base>=3.2.2
- plotnine>=0.8
- profilehooks>=1.12.0
- sphinx
- pytest
- pytest-cov
- pytest-mypy
name: snsim

