#!/bin/bash
#PBS -N {jobname}
#PBS -l select={nodes}:node_type=rome:mpiprocs={procs}
#PBS -l walltime={walltime}
#PBS -W group_list=s33594

cd $PBS_O_WORKDIR

#module load openmpi
#module load gcc/9.2.0  openmpi/4.0.4
module load python/3.8
module load mpi4py

OUTFILE=out/{jobname}-$PBS_JOBID-$(date +"%Y%m%dT%H%M").out
uniq $PBS_NODEFILE|wc -l > $OUTFILE
cat $PBS_NODEFILE|wc -l >>$OUTFILE

mpirun {mpiargs} python run.py {args} >$OUTFILE 2>&1