# HPC infrastructure
hpc_base_dir: $HOME
hpc_config:
  country_tz: Europe/Madrid
  workload_manager: SLURM

# TRAINING INFRASTRUCTURE ACCOUNT
hpc_credentials:
  host: 62.3.171.192
  user: <insert username>
  private_key: <insert private key>

hpc_job_prefix: SN_
hpc_monitor_period: 60
hpc_monitor_entrypoint: ""
hpc_skip_cleanup: False
hpc_workdir_prefix: SN_cfy
hpc_mpi_load_command: "false"
hpc_conda_activate_command: "source /work/miniconda3/bin/activate prop_mpi"


# Job specifications
job_skip_cleanup: True
job_option_type: "SBATCH"
#job_max_time: "01:00:00"
#job_num_nodes: 1
job_tasks_per_node: 20
job_partition: hidalgo
job_memory: 8G
job_id: 123


# Source code
git_repo: "https://github.com/sarming/propagation"
git_branch: "master"


# Input
topic: "neos"
graph_type: inner
sourcemap_url: "default" #requires some value, otherwise input variables are shuffled
stats_url: "default"

# Parameter learning
param_samples: 20
param_epsilon: 0.1

# Simulation
sim_features: 50
sim_sources: 3
sim_samples: 4


# CKAN
ckan_api_key: ""

learn_output_dataset:
  config: {entrypoint: "https://ckan.hidalgo-project.eu",  key: "<insert api key>"}
  dataset:
    #author: ''
    #license: GNU Free Documentation License
    id: <insert package id>
    #name: 
    #organization:
    #  name: 
    #resources:
    #  format: csv
    #private: true
    #state: active
    #title: 
    type: dataset
  type: ckan

sim_output_dataset:
  config: {entrypoint: "https://ckan.hidalgo-project.eu",  key: "<insert api key>"}
  dataset:
    #author: ''
    #license: GNU Free Documentation License
    id: <insert package id>
    #name:
    #organization:
    #  name: 
    #resources:
    #  format: csv
    #private: true
    #state: active
    #title: 
    type: dataset
  type: ckan
  


