name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ py39, py36 ]
        mpi: [ openmpi, mpich ]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          conda install -y -c conda-forge tox
      - name: Test with tox
        run: $CONDA/bin/tox -v -e ${{ matrix.python }}-${{ matrix.mpi }}