# HPC infrastructure
hpc_base_dir: $HOME
hpc_interface_config:
  country_tz: Europe/Madrid
  infrastructure_interface: SLURM

# TRAINING INFRASTRUCTURE ACCOUNT
hpc_host: 62.3.171.192
vault_user: sebastian
vault_token: {get_secret: sebastian_ckan }
hpc_private_key: {get_secret: sebastian_key}

hpc_job_prefix: SN_
hpc_monitor_period: 60
hpc_monitor_entrypoint: ""
hpc_skip_cleanup: False
hpc_workdir_prefix: SN_cfy
hpc_mpi_load_command: ":" # shell no-op
hpc_activate_command: "source /work/miniconda3/bin/activate prop_mpi"
hpc_internet_access: True


# Job specifications
job_skip_cleanup: False
#job_type: "SBATCH"
job_max_time: "01:00:00"
job_num_nodes: 1
job_tasks_per_node: 20
job_partition: hidalgo
job_memory: 8G
job_id: 123


# Source code
git_repo: "https://github.com/sarming/propagation"
git_branch: "master"


# Input
topic: "neos"
graph_type: "inner"
sourcemap_dataset_id: "527dac80-1d9b-44fd-b793-f546a246e531"
sourcemap_resource_name: "source_map.csv"
sourcemap_url: "default" #requires some value, otherwise input variables are shuffled
stats_dataset_id: "527dac80-1d9b-44fd-b793-f546a246e531"
stats_resource_name: "example_stats.csv"
stats_url: "default"

# Parameter learning
param_samples: 20
param_epsilon: 0.1

# Simulation
sim_features: 50
sim_sources: 3
sim_samples: 4


# CKAN
ckan_api_key:  { get_secret: sebastian_ckan }

ckan_resource_output:
  type: "file"
  name: "sna_output"
  description: "Output"
  format: "csv"
  url: "https://ckan.hidalgo-project.eu/dataset/test_out"

learn_output_dataset:
  config: { entrypoint: "https://ckan.hidalgo-project.eu",  key: {get_secret: sebastian_ckan } }
  dataset:
    #author: ''
    #license: GNU Free Documentation License
    id: test_out
    #name: 
    #organization:
    #  name: 
    #resources:
    #  format: csv
    #private: true
    #state: active
    #title: 
    type: dataset
  type: ckan

sim_output_dataset:
  config: { entrypoint: "https://ckan.hidalgo-project.eu",  key: {get_secret: sebastian_ckan } }
  dataset:
    #author: ''
    #license: GNU Free Documentation License
    id: test_out
    #name:
    #organization:
    #  name: 
    #resources:
    #  format: csv
    #private: true
    #state: active
    #title: 
    type: dataset
  type: ckan
  


